Aplicacion/Codigo y Pruebas/VideoOnDemand/VideoOnDemand.Web/Models/PaginatorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VideoOnDemand.Web.Models
{
    public class PaginatorViewModel<T> where T : class
    {
        public int TotalPages { get; set; }
        public int TotalRows { get; set; }
        public int Page { get; set; }
        public int PageSize { get; set; }
        public IEnumerable<T> Results { get; set; }
    }
}

Aplicacion/Codigo y Pruebas/VideoOnDemand/VideoOnDemand.Web/Controllers/MovieCatalogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VideoOnDemand.Web.Controllers
{
    public class MovieCatalogoController : Controller
    {
        // GET: MovieCatalogo
        public ActionResult Index()
        {
            return View();
        }
    }
}

Aplicacion/Codigo y Pruebas/VideoOnDemand/VideoOnDemand.Web/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoOnDemand.Entities;
using VideoOnDemand.Repositories;
using VideoOnDemand.Web.Helpers;
using VideoOnDemand.Web.Models;

namespace VideoOnDemand.Web.Controllers
{
    public class MovieController : BaseController
    {
        // GET: Movie
        public ActionResult Index()
        {
            var models = new List<MovieViewModel>().AsEnumerable();
            try
            {
                MovieRepository repository = new MovieRepository(context);

                //Consulte Los individuos del repositorio
                //var lst = repository.Query(x=>x.EstadosMedia==EEstatusMedia.VISIBLE);
                var lst = repository.Query(X=>X.EstadosMedia>0);
                //Mapeamos la lista de individuos con una lista de individuosViewModel
                models = MapHelper.Map<IEnumerable<MovieViewModel>>(lst);
            }
            catch (Exception ex)
            {

            }
            return View(models);//No olvidar
            
        }

        // GET: Movie/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Movie/Create
        public ActionResult Create()
        {
            //var model = new GeneroViewModel();
            //GeneroRepository generoRepository = new GeneroRepository(context);
            //var lst = generoRepository.GetAll();
            //model.AvailableGeneros = MapHelper.Map<ICollection<GeneroViewModel>>(lst);
            //return View(model);
            return View();
        }

        // POST: Movie/Create
        [HttpPost]
        public ActionResult Create(MovieViewModel model)
        {
                
            try
            {
                if (ModelState.IsValid)
                {
                    //Llamado al repositorio
                    MovieRepository repository = new MovieRepository(context);
                    #region Validaciones
                    //Validar Nombre Unico
                    var MovieQry = new Movie { Nombre = model.Nombre};

                    #endregion
                    //Mapear el modelo de vista a una entidad topic
                    Movie movie = MapHelper.Map<Movie>(model);
                    movie.EstadosMedia = EEstatusMedia.VISIBLE;
                    
                    repository.Insert(movie);
                    context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: Movie/Edit/5
        public ActionResult Edit(int id)
        {

            var repository = new MovieRepository(context);
                     
            var movie = repository.Query(x => x.MediaId == id).First();
            var model = MapHelper.Map<MovieViewModel>(movie);
            //Consultando topics ordenados por name

            return View(model);
        }

        // POST: Movie/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, MovieViewModel model)
        {
            //var topicRepository = new TopicRepository(context);
            try
            {
                var repository = new MovieRepository(context);

                if (ModelState.IsValid)
                {

                    var movie = MapHelper.Map<Movie>(model);
                    repository.Update(movie);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }

              
                return View(model);
            }
            catch (Exception ex)
            {
                
                return View(model);

            }
        }
        
        // GET: Movie/Delete/5
        public ActionResult Delete(int id)
        {
            MovieRepository repository = new MovieRepository(context);
            var movie = repository.Query(t => t.MediaId == id).First();
            var model = MapHelper.Map<MovieViewModel>(movie);//El objeto de entrada por uno de salida y se lo paso al modelo
            return View(model);//No lo olvides! regresalo a la vista
        }

        // POST: Movie/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, MovieViewModel model)
        {
            try
            {
                MovieRepository repository = new MovieRepository(context);
                var movie = repository.Query(t => t.MediaId == id).First();//Agrege esta linea
                //Mapear el modelo de vista a una entidad topic
                //Movie movies = MapHelper.Map<Movie>(model);
                movie.EstadosMedia = EEstatusMedia.ELIMINADO;
                repository.Update(movie);
                context.SaveChanges();


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Aplicacion/Codigo y Pruebas/VideoOnDemand/VideoOnDemand.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using VideoOnDemand.Web.Models;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Video On Demand!</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Video On Demand!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
<<<<<<< HEAD
                        <li>@Html.ActionLink("Películas", "Index", "MovieCatalogo")</li>
=======
                        <li>@Html.ActionLink("Películas", "Index", "Movie")</li>
>>>>>>> 81d96a0b6f8388a78a74f65eacc0e3ab021e0074
                        <li>@Html.ActionLink("Series", "Index", "Serie")</li>

                        var user = User.Identity;
                        var context = new ApplicationDbContext();
                        var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                        var s = UserManager.GetRoles(user.GetUserId());
                        //si es admin mostrar el menu administrar
                        if (s[0].ToString() == "Admin")
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
                                   aria-haspopup="true" 
                                   aria-expanded="false">Cat&aacute;logos <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Películas", "Index", "ManagePelicula")</li>
                                    <li>@Html.ActionLink("Series", "Index", "ManageSerie")</li>
                                    <li>@Html.ActionLink("Generos", "Index", "ManageGenero")</li>
                                    <li>@Html.ActionLink("Actores", "Index", "ManageActor")</li>
                                </ul>
                            </li>
                        }
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - VideoOnDemand</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Aplicacion/Codigo y Pruebas/VideoOnDemand/VideoOnDemand.Web/Views/Shared/_Paginator.cshtml
<nav aria-label="Page navigation">
    <ul class="pagination">
        @if (Model.Page > 1)
        {
            <li>
                <a href="@Url.Action(ViewBag.Action as string,new { page = Model.Page - 1 })" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        }
        else
        {
            <li class="disabled">
                <a href="@Url.Action(ViewBag.Action as string,new { page = Model.Page - 1 })" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        }
        @for (var index = 1; index <= Model.TotalPages; index++)
        {

            <li>@Html.ActionLink((index).ToString(), ViewBag.Action as string, new { page = index })</li>
        }
        @if (Model.Page < Model.TotalPages)
            {
            <li>
                <a href="@Url.Action(ViewBag.Action as string,new { page = Model.Page + 1 })" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        }
        else
        {
            <li class="disabled">
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        }

    </ul>
</nav>